plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md

remote_theme: pages-themes/slate@v0.2.0

title: CSSI-Cybertraining-SCIPE 2024 PI Meeting
description: Landing page for CCS 2024 PI Meeting
