title: NSF CSSI/CyberTraining/SCIPE PI Meeting
preposition: ''
description: >-
  August 12-13, 2024  /  Le Méridien Charlotte  /  Charlotte, NC
baseurl: "/ccs2024" # the subpath of your site, e.g. /blog
url: "https://confmeet.github.io" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: en
  show_errors: True

  link_preview:
    disable: false

  speakers:
    show_firstname: true

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true

  # Navigation bar
  navigation:
    logo:
      name:
      # img: ''
      url:
    breakpoint: md
    links:
      - name: Register & Poster Prep.
        relative_url: /registration/
      - name: Venue
        relative_url: /venue/
      - name: Program
        relative_url: /program/
      - name: Archives
        menu:
          - name: 2024 (current)
            disabled: true

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
      img: 'poster.png'
    links:
      - name: Registration
        relative_url: /registration/
      - name: Directions
        relative_url: /venue/
      - name: Program
        relative_url: /program/

  # Information boxes
  info_bars:
    - title: Program and Poster Schedule Available!
      color: primary
      main_only: true
      text: |
        - **[NEW]** Post-meeting survey is live! We appreciate your feedback! Please submit it using [the survey link](https://docs.google.com/forms/d/e/1FAIpQLSfmS4UXDHMxMptYuXQDIIP9_LZgX-s-lh8sDsu5ocCSOk5Nrw/viewform)
        - Access the Conference Program from the navigation bar.
        - View the poster schedules: [Session 1](https://docs.google.com/spreadsheets/d/1yeXYQdq2pFBFrvrEocplgUlkqyOWztpY/edit?gid=641226018#gid=641226018), [Session 2](https://docs.google.com/spreadsheets/d/1yeXYQdq2pFBFrvrEocplgUlkqyOWztpY/edit?gid=689414560#gid=689414560), and [Session 3](https://docs.google.com/spreadsheets/d/1yeXYQdq2pFBFrvrEocplgUlkqyOWztpY/edit?gid=1198973096#gid=1198973096)
        - Poster submission to Figshare due August 16.

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/venue'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Venue'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 35.2168, -80.8387142
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17
      popup_text: "555 S McDowell St Tower, Charlotte, NC 28204"

  talks:
    # Talk categories
    main_categories:
      - name: Poster
        color: warning
      - name: Panel
        color: dark
      - name: Breakout
        color: info
      - name: Talk
        color: primary
      - name: Others
        color: primary

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true
