title: NSF CSSI/CyberTraining/SCIPE PI Meeting
preposition: ''
description: >-
  August 12-13, 2024  /  Le Méridien Charlotte  /  Charlotte, NC
baseurl: "/cssi-ct-pi-meeting" # the subpath of your site, e.g. /blog
url: "https://cui.eecps.com" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - .github/
  - venv/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - screenshot.png
  - jekyll-theme-conference.gemspec
  - purgecss.config.js
  - _config.example.yml

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

# Theme default values
conference:
  lang: en
  show_errors: True

  link_preview:
    disable: false

  speakers:
    show_firstname: true

  program:
    url: '/program'
    time_steps: 15
    show_alltimes: true

  # Navigation bar
  navigation:
    logo:
      name:
      # img: ''
      url:
    breakpoint: md
    links:
      - name: Register & Poster Prep.
        relative_url: /registration/
      - name: Venue
        relative_url: /venue/
      - name: Program
        relative_url: /program/
      - name: Posters
        relative_url: /posters/
      - name: Speakers
        relative_url: /speakers/
      - name: Archives
        menu:
          - name: 2024 (current)
            disabled: true

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
      img: 'poster.png'
    links:
      - name: Registration
        relative_url: /registration/
      - name: Directions
        relative_url: /venue/
      - name: Program
        relative_url: /program/

  # Information boxes
  info_bars:
    - title: Abstract Submission, Registration, and Hotel Booking are Open
      color: primary
      main_only: true
      text: |
        - Abstract Submission: Complete this [form](https://docs.google.com/forms/d/e/1FAIpQLScz0MWEa4VdE8qreb1IOqfy5j3HnjH0DUR9lvSU5rR3FCi1Ig/viewform) by July 12.
        - Registration: Register [*at this link*](https://na.eventscloud.com/cssi-cyber24) by August 4th. Registration fee is $150 for each attendee.
        - Hotel booking:
          Please use the link for the NSF program sponsoring your project.

          - CSSI Program: [book here for group rate (194 USD per night)](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.marriott.com%2Fevents%2Fstart.mi%3Fid%3D1720731597456%26key%3DGRP&data=05%7C02%7Ch.cui%40okstate.edu%7Cae7d391b05034f04f0aa08dca1efbc7b%7C2a69c91de8494e34a230cdf8b27e1964%7C0%7C0%7C638563298266052510%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=3djcKaV7z6jAZuEPyC6fq98qX3mbrpS23wnBGH1iCkI%3D&reserved=0)
          - CyberTraining, CIP, SCIPE and others: [book here for group rate (194 USD per night)](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2Fwww.marriott.com%2Fevents%2Fstart.mi%3Fid%3D1720725959226%26key%3DGRP__%3B!!Mih3wA!CaRqBqTP1tfJIp8vO7w9FPeGHTi-aqEW3PVGIughze-K93rreYYbziI-1KS4TxsFvf63TZraeoZtaQrZOnnOBRFn%24&data=05%7C02%7Ch.cui%40okstate.edu%7C1b2e858079ea4d93aabd08dca1e7d1e9%7C2a69c91de8494e34a230cdf8b27e1964%7C0%7C0%7C638563264235254704%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=71wbwb6MInDB%2FuXsdKxKf8t7XJ96IwjfW0zBgCLpZMo%3D&reserved=0)
        - Poster submission due XXX. See instructions here.


  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/venue'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Venue'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 35.2168, -80.8387142
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17
      popup_text: "555 S McDowell St Tower, Charlotte, NC 28204"

  talks:
    # Talk categories
    main_categories:
      - name: Session 1
        color: info
      - name: Session 2
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true
